### ISSUE TITLE
To-Do List

### ISSUE THREAD

**Issue by realquantumcookie** [DarlingtonProgramming/FTC-Darbots-SkyStone#1]
This is a board for displaying to-be-implemented functionalities of the Darbots FTC Library. 
Discussions regarding future functionalities can take place here. 

---

- [x] Motor Controller
    - [x] Motor Controller Code
    - [x] Motor Contorller Test
- [ ] Integrated Functions
    - [x] Position Tracker Code
    - [x] Log Function Code
    - [ ] Position Tracker Test
    - [x] Log Function Test
- [x] Motion Contorller
    - [x] Motion Controller Code & RobotWheel Code
    - [x] Motion Controller Test
- [ ] ServoUsingMotor Controller
    - [x] ServoUsingMotor Code
    - [x] ServoUsingMotor_WithLimitSwitch Code
    - [x] ServoUsingMotor Test
    - [ ] ServoUsingMotor_WithLimitSwitch Test
- [ ] Chasis Programming
    - [x] Chassis Basic Control Class
    - [x] Omniwheel Chassis Code
    - [ ] Mechanum Chassis Code
    - [x] Omniwheel Chassis Test
    - [ ] Mechanum Chassis Test
    - [x] Gyro Guided Turn Code
    - [x] Gyro Guided Turn Test
    - [x] Gyro Guided Turn Optimization
- [ ] Block Programming Support(Off-Season)

**Comment by realquantumcookie** [comment]
✔ Solved
Updates on GyroGuidedTurn:
The test succeeded but the resulting angles are not satisfying. We are working on a error margin calculation optimization.

**Comment by realquantumcookie** [comment]
✔ Solved Oct 4, 2019
I think a little of reconstruction is needed here, probably.
There should be a GlobalUtil class that wraps up all Log / updateStatus functionalities by static methods, and if no running instance of DarbotsBasicOpMode is registered, those functions should return without throwing out an error.

**Comment by realquantumcookie** [comment]
Issue closed, new features will be posted as individual issues
